package com.github.composemusic.bean.playlist

data class Playlist(
    val id: Long,
    val name: String,
    val coverImgId: Long,
    val coverImgUrl: String,
    val coverImgId_str: String,
    val adType: Int,
    val userId: Long,
    val createTime: Long,
    val status: Int,
    val opRecommend: Boolean,
    val highQuality: Boolean,
    val newImported: Boolean,
    val updateTime: Long,
    val trackCount: Int,
    val specialType: Int,
    val privacy: Int,
    val trackUpdateTime: Long,
    val commentThreadId: String,
    val playCount: Long,
    val trackNumberUpdateTime: Long,
    val subscribedCount: Long,
    val cloudTrackCount: Int,
    val ordered: Boolean,
    val description: String,
    val tags: List<String>,
    val updateFrequency: Any,
    val backgroundCoverId: Long,
    val backgroundCoverUrl: Any,
    val titleImage: Long,
    val titleImageUrl: Any,
    val detailPageTitle: Any,
    val englishTitle: Any,
    val officialPlaylistType: Any,
    val copied: Boolean,
    val relateResType: Any,
    val coverStatus: Int,
    val subscribers: List<Any>,
    val subscribed: Boolean,
    val creator: Creator,
    val tracks: Any,
    val videoIds: Any,
    val videos: Any,
    val trackIds: Any,
    val bannedTrackIds: Any,
    val mvResourceInfos: Any,
    val shareCount: Long,
    val commentCount: Long,
    val remixVideo: Any,
    val newDetailPageRemixVideo: Any,
    val sharedUsers: Any,
    val historySharedUsers: Any,
    val gradeStatus: String,
    val score: Any,
    val algTags: Any,
    val distributeTags: Any,
    val trialMode: Int,
    val displayTags: Any,
    val displayUserInfoAsTagOnly: Boolean,
    val playlistType: String,
    val bizExtInfo: Any,

//    val lastSong: Any,
//    val officialTags: Any,
//    val recommendInfo: Any,
//    val recommendText: Any,
//    val shareStatus: Any,
//    val top: Boolean,
//    val totalDuration: Int,
//    val action: Any,
//    val actionType: Any,
//    val anonimous: Boolean,
//    val artists: Any,
//    val bookCount: Int,
)