package com.github.composemusic.bean.song

import com.github.composemusic.bean.albums.AlbumsBean
import com.github.composemusic.bean.artist.Artist

data class NewSongBean(
    val album: AlbumsBean,
    val alias: List<Any>,
    val artists: List<Artist>,
    val audition: Any,
    val bMusic: Any,
    val commentThreadId: String,
    val copyFrom: String,
    val copyright: Int,
    val copyrightId: Int,
    val crbt: Any,
    val dayPlays: Int,
    val disc: String,
    val duration: Int,
    val fee: Int,
    val ftype: Int,
    val hMusic: Any,
    val hearTime: Int,
    val hrMusic: Any,
    val id: Int,
    val lMusic: Any,
    val mMusic: Any,
    val mark: Int,
    val mp3Url: Any,
    val mvid: Int,
    val name: String,
    val no: Int,
    val noCopyrightRcmd: Any,
    val originCoverType: Int,
    val originSongSimpleData: Any,
    val playedNum: Int,
    val popularity: Int,
    val position: Int,
    val privilege: Any,
    val ringtone: String,
    val rtUrl: Any,
    val rtUrls: List<Any>,
    val rtype: Int,
    val rurl: Any,
    val score: Int,
    val sign: Any,
    val single: Int,
    val sqMusic: Any,
    val starred: Boolean,
    val starredNum: Int,
    val status: Int,
    val transName: Any
)