package com.github.composemusic.bean.user

data class Profile(
    val privacyItemUnlimit: Any,
//    val avatarDetail: Any,
    val detailDescription: String,
    val vipType: Int,
    val createTime: Long,
    val avatarImgId: Long,
    val birthday: Long,
    val gender: Int,
    val nickname: String,
    val djStatus: Int,
    val defaultAvatar: Boolean,
    val userType: Int,
    val province: Int,
    val city: Int,
    val backgroundImgId: Long,
    val avatarUrl: String,
    val followed: Boolean,
    val backgroundImgIdStr: String,
    val avatarImgIdStr: String,
    val backgroundUrl: String,
    val mutual: Boolean,
    val remarkName: String?,
    val authStatus: Int,
//    val experts: Any,
    val expertTags: List<String>?,
    val description: String,
    val userId: Int,
    val accountStatus: Int,
    val signature: String,
    val authority: Int,
    val followeds: Int,
    val follows: Int,
    val blacklist: Boolean,
    val eventCount: Int,
    val allSubscribedCount: Int,
    val playlistBeSubscribedCount: Int,
//    val followTime: Any?,
    val followMe: Boolean,
//    val artistIdentity: Any,
    val cCount: Int,
    val inBlacklist: Boolean,
    val sDJPCount: Int,
    val playlistCount: Int,
    val sCount: Int,
    val newFollows: Int,
)